<?php 
//echo password_hash("k",PASSWORD_DEFAULT);
//echo $poruka;
?>

<br />


<form  method="post" action="<?php echo App::config("url") ?>pocetna/search">
    <input type="search" name="search" value="<?php echo $_POST["search"]?>" placeholder="Pretražite oglasnik" />
    <input class="button" type="submit" value="Pretraži!" />
</form>


<div class="grid-x">
<?php foreach(Pocetna::read() as $selekcijaoglasa): ?>
<div class="callout cell large-2 columns" id="okvir">
        <i class="fas fa-<?php echo $selekcijaoglasa->ikona?>" id="kategorije_ikona"></i>
        <p id="kategorije_naziv">       
        <a href="<?php echo App::config("url") ?>pocetna/selekcija/<?php echo $selekcijaoglasa->sifra ?>">                
        <?php echo $selekcijaoglasa->naziv?></a>          
        </p>
    </div>
<?php endforeach;?>    
</div>