<div class="grid-x">
    <div class="large-12 medium-12 small-12 columns">
        <div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
            <button class="menu-icon" type="button" data-toggle="example-menu"></button>
            <div class="title-bar-title">Izbornik</div>
        </div>

        <div class="top-bar" id="example-menu">
            <div class="top-bar-left">
                <ul class="dropdown menu izbornikStavke" data-dropdown-menu>

                    <li>
                        <a href="<?php echo App::config("url")."index" ?>">Kategorije</a>

                    </li>
                    <?php if(Session::getInstance()->isLogiran()): ?>
                    <li>
                        <a href="<?php echo App::config("url")."kategorija/izlistaj" ?>">Uređuj kategorije</a>
                    </li>
                    <?php endif; ?>

                    <li>
                        <a href="<?php echo App::config("url")."pocetna/oglas" ?>">Oglasi</a>
                    </li>
                    <li>
                        <a href="#">O nama</a>
                        <ul class="menu vertical">
                    <li>
                        <a href="<?php echo App::config("url")."onama" ?>">O nama</a>
                    </li>
                    <li>
                        <a href="<?php echo App::config("url")."kontakt" ?>">Kontakt</a>
                    </li>
                    </ul>
                    </li>

                    <?php if(Session::getInstance()->isLogiran()): ?>
                    <li>
                        <a href="<?php echo App::config("url")."korisnik/index" ?>">Korisnici</a>
                    </li>
                    <li>
                        <a href="<?php echo App::config("url")."operater/index" ?>">Operateri</a>
                    </li>     

                    <li>
                        <a href="#">Moji oglasi</a>
                        <ul class="menu vertical">
                        <li>
                        <a href="<?php echo App::config("url")."oglas/prepareadd/"?><?php echo Session::getInstance()->getUser()->sifra ?>">Dodaj novi</a>
                    </li>
                            <li>
                            <a href="<?php echo App::config("url")."oglas/oglasKorisnik/"?><?php echo Session::getInstance()->getUser()->sifra ?>">Uredi oglase </a>
                            </li>
                        </ul>
                    </li>



                    <?php endif; ?>

                </ul>
            </div>
            <div class="top-bar-right">
                <ul class="menu izbornikStavke">                   
                    <li>
                        <?php if(Session::getInstance()->isLogiran()): ?>
                        <a href="<?php echo App::config("url") ?>admin/odjava">Odjava
                            <?php echo Session::getInstance()->getUser()->imePrezime ?>                            
                        </a>
                    <li>

                        <?php else:?>
                        <a href="<?php echo App::config("url")."registracija" ?>">Registracija</a>
                    </li>

                    <a href="<?php echo App::config("url") ?>admin/prijava">Prijava</a>
                    <?php endif;?>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>