<div class="callout" id="gornji">
   <p>PROFESIONALNI WEB DIZAJN</p>
</div>
<ul class="tabs" data-tabs id="example-tabs">
  <li class="tabs-title is-active"><a href="#panel1" aria-selected="true">Oglas</a></li>
  <li class="tabs-title"><a href="#panel2">Tab 2</a></li>
  <li class="tabs-title"><a href="#panel3">Tab 3</a></li>
  <li class="tabs-title"><a href="#panel4">Tab 4</a></li>
  <li class="tabs-title"><a href="#panel5">Tab 5</a></li>
  <li class="tabs-title"><a href="#panel6">Tab 6</a></li>
</ul>

<div class="tabs-content" data-tabs-content="example-tabs">
  <div class="tabs-panel is-active" id="panel1">
    <!-- <p>One</p> -->
    <p>Profesionalna izrada web stranica po vrlo prihvatljivim cijenama. Istaknite sebe i svoju tvrtku, prezentirajte proizvode online.
Sve naše stranice imaju responzivan dizajn (stranica se prilagođava zaslonu Vašeg mobitela, tableta, računala...)
Naša tehnička podrška je uvijek dostupna (24/7), te nas možete slobodno kontaktirati. 
<br />
Nudimo Vam: -izradu unikatnih web stranica
-web trgovine
-grafički dizajn
-izrada logotipa
-SEO optimizacija
-web hosting - prvu godinu besplatan
-registracija domene 
-fotografiranje vaših proizvoda/usluga sa profesionalnom opremom
-web marketing (Google AdWords, oglasavanje na društvenim mrežama...)</p>
  </div>
  <div class="tabs-panel" id="panel2">
    <p>Two</p>
    <img class="thumbnail" src="assets/img/generic/rectangle-7.jpg">
  </div>
  <div class="tabs-panel" id="panel3">
    <p>Three</p>
    <p>Check me out! I'm a super cool Tab panel with text content!</p>
  </div>
  <div class="tabs-panel" id="panel4">
    <p>Four</p>
    <img class="thumbnail" src="assets/img/generic/rectangle-2.jpg">
  </div>
  <div class="tabs-panel" id="panel5">
    <p>Five</p>
    <p>Check me out! I'm a super cool Tab panel with text content!</p>
  </div>
  <div class="tabs-panel" id="panel6">
    <p>Six</p>
    <img class="thumbnail" src="assets/img/generic/rectangle-8.jpg">
  </div>
</div>