Ova aplikacija je nastala u sklopu tečaja za Php programera u Edunovoj. Napravila ju je polaznica Kristina Terzić.
<br />
<br />
Aplikacija je zamišljena kao oglasnik kreativnih usluga. Sadržaj svih oglasa ne predstavlja kontakte i informacije o stvarnim osobama, već je generičke prirode da pokaže funkcionalnost stranice. 
<br />
<br />
Sve fotografije koje se nalaze u oglasima su preuzete sa stranice <a href="https://unsplash.com/">https://unsplash.com/</a>

