<?php foreach($oglasi as $selekcija): ?>
  <div class="columns medium-5">
    <h3 class="work-feature-block-header"><?php echo $selekcija->naziv ?></h3>
    <p><?php echo $selekcija->tekstponude ?></p>
    <h4>Detalji</h4>
    <ul>
      <li>Korisničko ime: <?php echo $selekcija->korisnik ?></li>
      <li>Datum objavljivanja oglasa: <?php echo date("d.m.Y.",strtotime($selekcija->pocetnidatum))?></li>
      <li>Telefon: <?php echo $selekcija->telefon ?></li>
      <li>Email: <?php echo $selekcija->email ?></li>
    </ul>
    <div class="work-feature-block row">
  <div class="columns medium-7">
    <img class="work-feature-block-image" src="/public/img/<?php echo $selekcija->sifra ?>.png"/>
  </div>
  </div>
</div>
<?php endforeach; ?>


<!-- 
<nav aria-label="Pagination">
  <ul class="pagination text-center">
    <li class="pagination-previous"><a href="<?php // echo App::config("url") ?>pocetna/selekcija/<?php// echo $prethodna ?>" aria-label="Next page">Prethodna <span class="show-for-sr">page</span></a></li>
    <li class="pagination-next"><a href="<?php //echo App::config("url") ?>pocetna/selekcija/<?php// echo $sljedeca ?>" aria-label="Next page">Sljedeća <span class="show-for-sr">page</span></a></li>
  </ul>
</nav> -->