<?php foreach($oglasi as $selekcija): ?>
  <div class="columns medium-5">
    <h3 class="work-feature-block-header"><?php echo $selekcija->naziv ?></h3>
    <p><?php echo $selekcija->tekstponude ?></p>
    <h4>Detalji</h4>
    <ul>
      <li>Korisničko ime: <?php echo $selekcija->korisnik ?></li>
      <li>Datum objavljivanja oglasa: <?php echo date("d.m.Y.",strtotime($selekcija->pocetnidatum))?></li>
      <li>Telefon: <?php echo $selekcija->telefon ?></li>
      <li>Email: <?php echo $selekcija->email ?></li>
    </ul>
    <?php if(Session::getInstance()->isLogiran()): ?>
    <a href="#features" class="alert button">Ocijeni!</a>
    <?php endif; ?>

    <?php if(Session::getInstance()->getUser()->uloga==="admin"): ?>    
    <a style="color: red;" href="<?php echo App::config("url") ?>oglas/brisanje/<?php echo $oglas->sifra ?>">
        <i class="fas fa-trash fa-2x"></i></a>         
  <?php endif; ?>



    <div class="work-feature-block row">
  <div class="columns medium-7">
    <img class="work-feature-block-image" src="/public/img/oglasi/<?php echo $selekcija->sifra ?>.png"/>
  </div>
  </div>
</div>
<?php endforeach; ?>

