<label>Korisničko ime
    <input type="text" name="korisnickoime" 
    value="<?php echo Request::post("korisnickoime") ?>" />
  </label>

  <label>Ime
    <input type="text" name="ime"
    value="<?php echo Request::post("ime") ?>" />
  </label>

  <label>Prezime
    <input type="text" name="prezime"
    value="<?php echo Request::post("prezime") ?>" />
  </label>

  <label>Email
    <input type="text" name="email"
    value="<?php echo Request::post("email") ?>" />
  </label>

  <label>Telefon
    <input type="text" name="telefon"
    value="<?php echo Request::post("telefon") ?>" />
  </label>
 
  <label> Lozinka
  <input class="input-group-field" id="password" name="lozinka" type="password" required value="<?php echo Request::post("lozinka") ?>">
  </label>  
  
  <label>OIB
    <input type="number" name="oib"
    value="<?php echo Request::post("oib") ?>" />
  </label>

    <label>Datum rođenja
    <input type="date" name="datumrodenja"
    value="<?php if(Request::post("datumrodenja")!=null){
      echo date("Y-m-d",strtotime(Request::post("datumrodenja")));
    } ?>" />
  </label>

      <label>O meni
    <input type="text" name="omeni"
    value="<?php echo Request::post("omeni") ?>" />
  </label>

  <label>Profilna slika
    <input type="file" name="slika"  />
  </label>
