<label>Korisničko ime
    <input type="text" name="korisnickoime" 
    value="<?php echo Request::post("korisnickoime") ?>" />
  </label>

  <label>Ime
    <input type="text" name="ime"
    value="<?php echo Request::post("ime") ?>" />
  </label>

  <label>Prezime
    <input type="text" name="prezime"
    value="<?php echo Request::post("prezime") ?>" />
  </label>

  <label>Email
    <input type="text" name="email"
    value="<?php echo Request::post("email") ?>" />
  </label>

  <label>Telefon
    <input type="text" name="telefon"
    value="<?php echo Request::post("telefon") ?>" />
  </label>
