<form class="log-in-form" method="post" 
action="<?php echo App::config("url") ?>kategorija/add">

 <?php include_once "kontrole.phtml" ?>
 
 <div class="grid-x">
    <div class="large-6 columns" style="padding: 10px;">
        <a href="<?php echo App::config("url") ?>kategorija/izlistaj" class="alert button expanded">Odustani</a>
    </div>
    <div class="large-6 columns"  style="padding: 10px;">
        <input type="submit" class="button expanded" value="Dodaj novu kategoriju" />
    </div>
 </div>
  
 

</form>
<?php echo $poruka ?>
