<?php foreach(Oglas::read() as $oglas): ?>
<div class="grid-x">
    <div class="large-8 columns" style="padding: 10px;">

        <table>
            <div class="callout alert">
                <h5></h5>
                <p><?php echo $oglas->naziv?></p>
            </div>
            <thead>
                <tr></tr>
            </thead>
            <tbody>
                <tr>
                    <td>Kategorija:</td>
                    <td><?php echo $oglas->kategorija?></td>
                </tr>
                <tr>
                    <td>Vrsta:</td>
                    <td><?php echo $oglas->vrsta?></td>
                </tr>
                <tr>
                    <td>Korisnik:</td>
                    <td><?php echo $oglas->korisnik?></td>
                </tr>
                <tr>
                    <td>Datum objavljivanja:</td>
                    <td><?php echo $oglas->pocetnidatum?></td>
                </tr>
            </tbody>
        </table>
        <div class="callout secondary">
            <h5></h5>
            <p><?php echo $oglas->tekstponude?></p>
        </div>


    </div>
</div>
<?php endforeach;?>