<label>Korisničko ime
    <input type="number" name="korisnik" 
    value="<?php echo Request::post("korisnik") ?>" />
  </label>

  <label>Vrsta oglasa
    <input type="text" name="vrsta"
    value="<?php echo Request::post("vrsta") ?>" />
  </label>

  <label>Naslov oglasa
    <input type="text" name="naziv"
    value="<?php echo Request::post("naziv") ?>" />
  </label>

  <label>Tekst oglasa
    <input type="text" name="tekstponude"
    value="<?php echo Request::post("tekstponude") ?>" />
  </label>

  <label>Kategorija
    <input type="number" name="kategorija"
    value="<?php echo Request::post("kategorija") ?>" />
  </label>
 