<?php foreach($moji as $oglas): ?>
<div class="grid-x">
    <div class="large-8 columns" style="padding: 10px;">

        <table>
            <div class="callout alert">
                <h5></h5>
                <p><?php echo $oglas->naziv?></p>
            </div>
            <p><?php echo $oglas->sifra?></p>                      
            <thead>
                <tr></tr>
            </thead>
            <tbody>
                <tr>
                    <td><a href="<?php echo App::config("url") ?>oglas/promijeni/<?php echo $oglas->sifra ?>">
                    <i class="fas fa-edit fa-2x"></i></a></td>
                    <td><a style="color: red;"
                    href="<?php echo App::config("url") ?>oglas/brisanje/<?php echo $oglas->sifra ?>">
                    <i class="fas fa-trash fa-2x"></i></a></td>
                </tr>
                <tr>
                    <td>Kategorija:</td>
                    <td><?php echo $oglas->kategorija?></td>
                </tr>
                <tr>
                    <td>Vrsta:</td>
                    <td><?php echo $oglas->vrsta?></td>
                </tr>
                <tr>
                    <td>Korisnik:</td>
                    <td><?php echo $oglas->korisnik?></td>
                </tr>
                <tr>
                    <td>Datum objavljivanja:</td>
                    <td><?php echo date ("d. m. Y.",strtotime($oglas->pocetnidatum)) ?></td>
                </tr>
            </tbody>
        </table>
        <div class="callout secondary">
            <h5></h5>
            <p><?php echo $oglas->tekstponude?></p>
        </div>


    </div>
</div>
<?php endforeach;?>