<?php foreach($moji as $oglas): ?>
<div class="columns medium-5">
    <h3 class="work-feature-block-header"><?php echo $oglas->naziv ?></h3>
    <p><?php echo $oglas->tekstponude ?></p>
    <h4>Detalji</h4>
    <ul>
        <li>Korisničko ime: <?php echo $oglas->korisnik ?></li>
        <li>Datum objavljivanja oglasa: <?php echo date("d.m.Y.",strtotime($oglas->pocetnidatum))?></li>
        <li>Telefon: <?php echo $oglas->telefon ?></li>
        <li>Email: <?php echo $oglas->email ?></li>
    </ul>
    <div class="work-feature-block row">
        <div class="columns medium-7">
            <img class="work-feature-block-image" src="/public/img/<?php echo $oglas->sifra ?>.png" />
        </div>
        <div>
            <br />
            <p>Uredi oglas<a href="<?php echo App::config("url") ?>oglas/promijeni/<?php echo $oglas->sifra ?>">
                    <i class="fas fa-edit fa-2x"></i></a></p>
            <p>Obriši oglas<a style="color: red;" href="<?php echo App::config("url") ?>oglas/brisanje/<?php echo $oglas->sifra ?>">
                    <i class="fas fa-trash fa-2x"></i></a></p>
        </div>
    </div>
</div>
<?php endforeach; ?>